name: CI

on:
  fork:
    branches:
      - main  # This will trigger on fork

jobs:
  setup_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl git

      - name: Clone Move repository
        run: |
          git clone https://github.com/move-language/move.git
          cd move
          ./scripts/dev_setup.sh -ypt
          source ~/.profile

      - name: Install Move CLI
        run: |
          cd move/language/tools
          cargo install --path move-cli

      - name: Verify Move installation
        run: move --help

      - name: Run unit tests
        run: |
          cd path/to/your/move/project
          move test
